#SPDX-License-Identifier: MIT-0
---
# handlers file for machinemonkeys.rocky_router
- name: Reload firewall
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false

- name: Reload dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: reloaded
