# SPDX-License-Identifier: MIT-0
---
# handlers file for machinemonkeys.rocky_router
- name: Reload firewall
  ansible.builtin.command: firewall-cmd --reload
  changed_when: false

- name: Restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted

- name: Reload ssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: LAN UP
  community.general.nmcli:
    conn_name: "{{ rocky_router_ifs.lan_bridge }}"
    state: up

- name: WAN UP
  community.general.nmcli:
    conn_name: "{{ rocky_router_ifs.wan }}"
    state: up
